### ISSUE TITLE
node_distance_to does not behave as expected

### ISSUE THREAD

**Issue by holgerbrandl** [thomasp85/tidygraph#100]
In the given example, I'd expect increasing distances up to c and g, but the result is different. 

* For e no distance is calculated but it should be 2 since the closest node is g.
* g should have distance 0.

It seems that `node_distance_to` does not support a list of nodes as argument (for which the minimal distance would be reported)?

```
nodes = data_frame('id' = c('A', "B", "C", "D"))

links = tribble(
~ from, ~ to,
"A" , "B",
"B", "C",
"C", "D",
"D", "E",
"E", "F",
"F", "G",
"G", "H"
)

net = links %>%  as_tbl_graph(directed=T)

qnIdx = activate(net, nodes) %>% pull(name) %>% { which(. %in% c("C", "G")) }

net %>%
    activate(nodes) %>%
    mutate(source_dist = node_distance_to(nodes = qnIdx)) %>%
    ggraph(layout = "kk") +
    geom_edge_link(arrow = arrow(length = unit(8, 'mm'))) +
    # geom_node_point(aes(size = source_dist), alpha=.4) +
    geom_node_text(aes(label = name, color=source_dist), size=10) +
    theme_graph(fg_text_colour = 'white', base_family = 'Helvetica')
```
![image](https://user-images.githubusercontent.com/200952/63941121-391ca200-ca6b-11e9-9824-e28e63bf4d3b.png)

**Comment by thomasp85** [comment]
`qnIdx` is `c(3, 7)` which is then recycled to match the length of the nodes (8). It seems correct to me:

```r
with_graph(net, node_distance_to(c(3, 7)))
#> [1]   2   5   0   3 Inf   1 Inf Inf
```

**Comment by holgerbrandl** [comment]
I see. I've missed the comment about the recycling in the docs. It may be personal taste, but the argument naming `nodes` seems to somehow imply that each node in the graph is compared against a set of nodes provided by the argument (which is not the case as I understand now)

My actual usecase is to calculate the shortest distance to a source node in a directed graph that contains multiple sources nodes.  `node_distance_to` does not seem to provide such function because of the recycling, is there another way of calculating it using `tidygraph`?

**Comment by mbojan** [comment]
See also #112 .

**Comment by thomasp85** [comment]
There is not one right now. I never quite settled on the correct return type for this. But hopefully in a future release

**Comment by holgerbrandl** [comment]
Thanks for the pointer @mbojan . Indeed it's reporting exactly the same bug/mental problem. Feel welcome to close this ticket as a duplicate. 

Now, since I have understood the recycling aspect, one could also argue that comparing each row against all elements in `nodes` to calculate _just_ the shortest distance would be incorrect since no aggregation function is provided. Other types of aggregation (max, mean) in case of multiple distances are legit as well. 

However, imho (a) removing the recycling (which does not seem to serve a sensible purpose from a user perspective) and (b) adding an optional argument to define the method for distance aggregation with `min` as default would seem the most intuitive and correct API here.

**Comment by Steviey** [comment]
+1

**Comment by thomasp85** [comment]
>which does not seem to serve a sensible purpose from a user perspective
This is your personal preference speaking, not an objective statement. The API in tidygraph is pretty stringent and consistent and all of these functions works in the same way. I do agree the other functionality is also useful but that would need a different idiom

**Comment by MatthieuStigler** [comment]
I fell in the same trap, wrongly assuming that providing two target nodes would the minimum distance to any node. And I agree using `nodes` can be a but confusing when only one node is provided

is there any chance you could issue a warning when `length(nodes)>1` in `node_distance_to`, instead of silently recycling? Thanks!
