### ISSUE TITLE
`augment_edges` to add vertex attributes to edges

### ISSUE THREAD

**Issue by colin-fraser** [thomasp85/tidygraph#104]
Thanks for the fantastic package!

I've found myself in the situation of wanting to take vertex attributes and put them in the edge list often, and I wrote a function for doing it quickly. Here's the basic behavior I'm trying to get.

```
set.seed(1729)

g <- play_barabasi_albert(100, 1) %>% 
  mutate(degree = centrality_degree(), 
         node_type = sample(c('A', 'B', 'C'), size = 100, replace = TRUE))

g

# A tbl_graph: 100 nodes and 99 edges
#
# A rooted tree
#
# Node Data: 100 x 2 (active)
  degree node_type
   <dbl> <chr>    
1      0 A        
2      1 C        
3      1 C        
4      1 A        
5      1 B        
6      1 A        
# … with 94 more rows
#
# Edge Data: 99 x 2
   from    to
  <int> <int>
1     2     1
2     3     1
3     4     1
# … with 96 more rows

##### augment edges with node_type
g %>% 
  augment_edges(node_type)

# A tbl_graph: 100 nodes and 99 edges
#
# A rooted tree
#
# Node Data: 100 x 2 (active)
  degree node_type
   <dbl> <chr>    
1      0 A        
2      1 C        
3      1 C        
4      1 A        
5      1 B        
6      1 A        
# … with 94 more rows
#
# Edge Data: 99 x 4
   from    to node_type_from node_type_to
  <int> <int> <chr>          <chr>       
1     2     1 C              A           
2     3     1 C              A           
3     4     1 A              A           
# … with 96 more rows

##### augment edges with node_type and degree
g %>% 
  augment_edges(node_type, degree)

# A tbl_graph: 100 nodes and 99 edges
#
# A rooted tree
#
# Node Data: 100 x 2 (active)
  degree node_type
   <dbl> <chr>    
1      0 A        
2      1 C        
3      1 C        
4      1 A        
5      1 B        
6      1 A        
# … with 94 more rows
#
# Edge Data: 99 x 6
   from    to node_type_from degree_from node_type_to degree_to
  <int> <int> <chr>                <dbl> <chr>            <dbl>
1     2     1 C                        1 A                    0
2     3     1 C                        1 A                    0
3     4     1 A                        1 A                    0
# … with 96 more rows

##### how many edges go between each node_type?
g %>% 
  augment_edges(node_type) %>% 
  activate(edges) %>% 
  as_tibble() %>%
  count(node_type_from, node_type_to)

# A tibble: 9 x 3
  node_type_from node_type_to     n
  <chr>          <chr>        <int>
1 A              A                7
2 A              B                7
3 A              C               12
4 B              A                8
5 B              B               12
6 B              C               14
7 C              A               14
8 C              B               16
9 C              C                9

```

For the type of work I use this package for, this is hugely valuable.

If this looks useful, I do have a simple implementation. Not 100% sure it's the best way, but maybe it's a jumping off point?

```
augment_edges <- function(.data, ...) {
  
  to_join <- select(.data, ...) %>% 
    mutate(.id = row_number())
  .data %>% 
    activate(edges) %>% 
    left_join(
      dplyr::rename_at(to_join, dplyr::vars(-.id), list(~paste0(., '_from'))), 
      by = c('from' = '.id'), copy = TRUE
      ) %>% 
    left_join(
      dplyr::rename_at(to_join, dplyr::vars(-.id), list(~paste0(., '_to'))), 
      by = c('to' = '.id'), copy = TRUE
    )
}
```

**Comment by mkoohafkan** [comment]
Note that the `.N()` function allows you to query node attributes within `mutate` operations on edge (node) tables, so the joining isn't needed; just use the `from` and `to` indices to pull the associated node attributes.

**Comment by colin-fraser** [comment]
I thought of that, but I (maybe naively, not having dug around in .N() too
much) thought that building the edge attributes separately and then joining
once would be more performant than, say, looping or lapplying through all
the arguments and adding them to the data frame one at a time.

**Comment by thomasp85** [comment]
Yeah, that would be my recommendation. You are free to use your own function of course, but I don’t think I’ll have it in tidygraph as such functionality is already pretty easy

**Comment by colin-fraser** [comment]
Right, but I want to do this for arbitrarily many possible node attributes
passed in the ... argument of the function. You didn't loop because you
knew explicitly that you were going to add those two attributes, but to
make it general you would have to loop through the attributes and call .N()
twice per attribute. Anyway, here you called .N() four times. I suspect
this is slower for a large graph than operating on the node data frame
directly and then joining once.

**Comment by thomasp85** [comment]
You can also use `.N()` directly one a left join, but unless you can detect actual performance degradation you shouldn’t worry about calling it multiple times (it won’t copy any data, just present it as a data.frame).

If your function is useful to you then you should definitely continue using it, but I don’t think it should be part of tidygraph proper
