### ISSUE TITLE
`node` argument to `map_local` does not refer to actual node index in neighborhood graph

### ISSUE THREAD

**Issue by mkoohafkan** [thomasp85/tidygraph#107]
When using `map_local` with an arbitrary function `.f`, the value of the argument `node` corresponds to the node's index in `graph`, not in `neighborhood`. This means that you cannot use the `node` argument for selections on the `neighborhood` graph.

```r
library(tidyverse)
library(tidygraph)
n = create_ring(5, directed = TRUE) %N>% 
  mutate(name = paste0("node_", 1:n())) %N>% 
  mutate(nbd = map_local(1, .f = function(neighborhood, graph, node) 
      neighborhood %N>%
      mutate(this.node = node)
    )
  )

n %N>% pull(nbd) %>% pluck(5)
#> # A tbl_graph: 3 nodes and 2 edges
#> #
#> # A rooted tree
#> #
#> # Node Data: 3 x 2 (active)
#>   name   this.node
#>   <chr>      <int>
#> 1 node_1         5
#> 2 node_4         5
#> 3 node_5         5
#> #
#> # Edge Data: 2 x 2
#>    from    to
#>   <int> <int>
#> 1     2     3
#> 2     3     1
```
As shown in this example, the node index in the main graph is 5 but there are only 3 nodes in the neighborhood graph of node 5 (node 5 becomes node 3 in `neighborhood`). This  essentially means that functions on local neighborhoods relying on the node index for operations (e.g. further edge filtering or operations that use attributes of the target node) must be performed on the full `graph`, since the node indices of the `neighborhood` differ from the original graph and no longer correspond to the value of `node`.

Some of this could probably be resolved by supporting node names in the edge list or maintaining a fixed node index in `tbl_graph` objects, as (tangentially) discussed in #103.

**Comment by thomasp85** [comment]
`neighborhood` now contains a `.central_node` node attribute that is true for the node the neighbourhood belongs to
