### ISSUE TITLE
feature request: edge_is_bridge()

### ISSUE THREAD

**Issue by wdkrnls** [thomasp85/tidygraph#113]
Could edge_is_bridge() be added as an edge type? This would return TRUE when the edge is a [bridge](https://en.wikipedia.org/wiki/Bridge_(graph_theory)). I would like to split my graph into separate components by eliminating bridge edges, but this does not appear to be easy to do.

There doesn't seem to be an easy way to find bridges using the R interface to igraph either.  However, maybe someone knows how to implement this with `map_dfs_back`?

**Comment by wdkrnls** [comment]
Bridges can be found using `igraph::biconnected_components`! Thank you to Szabolcs Horvát for pointing me to it. The following code worked on my graph:

```r
my_bridges = 
  suppressWarnings({
    my_tidy_graph %>%
      igraph::biconnected_components() %>%
      purrr::pluck("components") %>%
      purrr::keep(~ length(.x) == 2) %>%
      purrr::map(~ tibble(to = .x[1], from = .x[2])) %>%
      dplyr::bind_rows()
  })

my_tidy_graph %E>%
  dplyr::left_join(my_bridges %>% mutate(bridge = TRUE), by = c("from", "to")) %>%
  dplyr::mutate(bridge = ifelse(is.na(bridge), FALSE, bridge)) %>%
  ggraph::ggraph() +
  ggraph::geom_edge_link(aes(edge_color = bridge)) +
  ggraph::geom_node_point(alpha = 0.3) +
  ggraph::geom_node_text(aes(label = name), nudge_y = 0.5, repel = TRUE) +
  ggplot2::theme(legend.position = "bottom") +
  ggraph::scale_edge_color_manual(values = c("black", "red3"))
```
Maybe it could be used to implement `edge_is_bridge`?

**Comment by thomasp85** [comment]
I like that... I'll look into it for the next release

**Comment by wdkrnls** [comment]
Actually, you've already done better:

```r
my_tidy_graph %E>%
  mutate(cluster = group_biconnected_component()) %>%
  group_by(cluster) %>%
  mutate(nmembers = n(),
         bridge = nmembers == 1) %>%
  ggraph() +
  geom_edge_link(aes(edge_color = bridge)) +
  geom_node_point(alpha = 0.3) +
  geom_node_text(aes(label = name), nudge_y = 0.5, repel = TRUE) +
  theme(legend.position = "bottom") +
  scale_edge_color_manual(values = c("black", "red3"))
```

**Comment by wdkrnls** [comment]
Having `node_is_articulate` might be nice as well.

**Comment by szhorvat** [comment]
@thomasp85  igraph 1.3.0 has the `bridges()` function now, you just need to expose it.

**Comment by thomasp85** [comment]
@wdkrnls articulation points are exposed through `node_is_cut()`
