### ISSUE TITLE
Best way to add node attributes to only certain nodes

### ISSUE THREAD

**Issue by karrtikiyer-tw** [thomasp85/tidygraph#116]
I have a graph where nodes could be of different type whereby each one could have different set of attributes. I  am looking for the best way to add additional node properties to a particular set of nodes in my graph.

**Comment by thomasp85** [comment]
there really is no way for nodes to have separate sets of attributes... You can set an attribute to `NA` for nodes that doesn't have this attribute, but that is the extent of it
