### ISSUE TITLE
Additional dplyr 1.0.0 Change: Add group_vars() method

### ISSUE THREAD

**Issue by billdenney** [thomasp85/tidygraph#119]
As discussed in sfirke/janitor#370, please also add a `group_vars()` method.  This is copied from that issue.

Tagging other interested parties from the janitor issue: @hadley, @romainfrancois

**Comment by sfirke** [comment]
I just got an auto notification email about the failing tidygraph test in janitor, caused by dplyr 1.0.0 and referenced in janitor issue 370 above.  So bumping this here.
