### ISSUE TITLE
as_symbol from rlang

### ISSUE THREAD

**Issue by mdsumner** [thomasp85/tidygraph#13]
Sorry for the terse message, I had previously worked around this by changing the imports for tidygraph, then put it aside and forgot. 

I hope to get back to this and report better, but in case it's an obvious fix here's what I see: 

```
Error : object 'as_symbol' is not exported by 'namespace:rlang'
```

**Comment by thomasp85** [comment]
rlang has been a moving target. Will clean it up now that it is on CRAN

**Comment by thomasp85** [comment]
should be fixed now
