### ISSUE TITLE
node data in long format

### ISSUE THREAD

**Issue by kkmann** [thomasp85/tidygraph#136]
Hey,

I just stumbled over 

```
tbl_graph(nodes = tibble(id = c("a", "a", "b", "b"), t = c(1, 2, 1, 2)), edges = tibble(from = "a", to = "b"), node_key = "id")
# A tbl_graph: 4 nodes and 1 edges
#
# A rooted forest with 3 trees
#
# Node Data: 4 x 2 (active)
  id        t
  <chr> <dbl>
1 a         1
2 a         2
3 b         1
4 b         2
#
# Edge Data: 1 x 2
   from    to
  <int> <int>
1     1     3
```

I expected a graph of two nodes ("a" and "b") with longitudinal information (t) in long format. It seems that the input is interpreted as a graph with four nodes (which would still be fine) but the edge data is incomplete (would expect an edge from 2 to 4). I was hoping to use this structure to show node data over time with facet_nodes(~t). Is long-format node data supported and if so, what am I missing?

edit: I realized this might be better suited for the rstudio forum, cross-posted it [here](https://community.rstudio.com/t/long-format-node-data-in-tidygraphs-longitudinal-node-wrapping/93522).

Thanks!

**Comment by luukvdmeer** [comment]
This is not possible indeed (at least as far as I know). The tbl_graph class subclasses igraph and simply *exposes* the data in a tidy manner, as if they were tibbles.

In igraph, attributes of nodes (referred to as vertices in igraph) are stored as a named list, in which each element refers to a specific attribute. Each attribute, in turn, has as many elements as the number of nodes in the network. The first element refers to the specific attribute value of the first node, the second to the second node, etc. That means that each node can only have a single value per attribute. There is no possibility to have multiple values of the same attribute referring to the same node.

In the tbl_graph structure this means that each node is identified by a single row in the nodes table. It is not possible to have multiple rows refer to the same node. The node_key argument is meant to refer to a character encoded column in the nodes table with *unique values*, and apparently it gets confused when the values in the referred column are not unique, and simply only considers the first match. This seems to be not clearly documented anywhere, indeed.

Your options could be:

1) Using a wide format, hence having separate columns `t1` and `t2`. I know this is not so much in line with the tidy data structure, but a tidy data structure simply does not fit every possible use-case.

2) Creating a separate network for each time stamp, and then joining these networks. Node a at t = 1 will then be viewed as a different node than node a at t = 2, but your edge data would be correct. Probably you want to do this in some sort of loop if you have a lot of timestamps.

``` r
library(tidyverse)
library(tidygraph)
#> 
#> Attaching package: 'tidygraph'
#> The following object is masked from 'package:stats':
#> 
#>     filter

nodes = tibble(id = c("a", "a", "b", "b"), t = c(1, 2, 1, 2))
edges = tibble(from = "a", to = "b")

G1 = tbl_graph(filter(nodes, t == 1), edges, node_key = "id")
G2 = tbl_graph(filter(nodes, t == 2), edges, node_key = "id")

graph_join(G1, G2, by = c("id", "t"))
#> # A tbl_graph: 4 nodes and 2 edges
#> #
#> # A rooted forest with 2 trees
#> #
#> # Node Data: 4 x 2 (active)
#>   id        t
#>   <chr> <dbl>
#> 1 a         1
#> 2 b         1
#> 3 a         2
#> 4 b         2
#> #
#> # Edge Data: 2 x 2
#>    from    to
#>   <int> <int>
#> 1     1     2
#> 2     3     4
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kkmann** [comment]
Hey, thanks! That is really unfotunate although I see the benefits of the design choice of sticking with igraph underneath...
