### ISSUE TITLE
Suggestion: play_gnm and play_gnp

### ISSUE THREAD

**Issue by szhorvat** [thomasp85/tidygraph#152]
This is just a small suggestion to separate `play_erdos_renyi` into `gnm` and `gnp` versions. This is what the modern interface does as well in igraph, see `sample_gnm` and `sample_gnp` (`erdos.renyi.game` is deprecated). Mixing up the two in a single function is not particularly productive. Also, while today both the G(n,p) and G(n,m) are sometimes referred to as the Erdős-Rényi model, the original paper of Erdős and Rényi actually considered G(n,m), not G(n,p).

**Comment by szhorvat** [comment]
Thanks! It's good that this was done, as in a future version of igraph, the parameters of `sample_gnm()` and `sample_gnp()` will diverge (the former will get an extra parameter, but not the latter).

**Comment by szhorvat** [comment]
Also, just in case you are preparing a new release, be aware that a new version of igraph is coming very soon, with some deprecations and small breaking changes (no breakage revealed in tidygraph _yet_ due to this but you never know...) You might want to wait for that release.

**Comment by thomasp85** [comment]
Thanks for the heads up - do you know the timeframe of the igraph release?
