### ISSUE TITLE
Argument `neimode` is deprecated; use `mode` instead

### ISSUE THREAD

**Issue by metanoid** [thomasp85/tidygraph#156]
The `map_bfs_*` family of functions seem to be using an older version of the `{igraph}` API.
See warning messages auto-generated here:
https://thomasp85.r-universe.dev/articles/ggraph/Edges.html#meet-the-geom_edge_-family

```r
## Warning in bfs(graph = graph, root = root, neimode = mode, unreachable =
## unreachable, : Argument `neimode' is deprecated; use `mode' instead
```

**Comment by luisdza** [comment]
It looks like we needed a find and replace.
Deprecation was initiated with issue: https://github.com/igraph/rigraph/issues/495

I have created a pull request with the change and tested with the example from https://thomasp85.r-universe.dev/articles/ggraph/Edges.html#meet-the-geom_edge_-family
