### ISSUE TITLE
intergraph package can handle igraph <-> network conversions

### ISSUE THREAD

**Issue by briatte** [thomasp85/tidygraph#17]
It's all in the title: if you need a quick way to support `network::network`, the `intergraph` can handle that. Supports both uni- and bipartite graphs if memory serves.

P.S. Your work on `ggraph` and `tidygraph` is awesome and inspiring. Thumbs up!

**Comment by thomasp85** [comment]
Thanks :-)

I'm aware of `intergraph` but as I already had some conversion code for network->igraph I decided to avoid another dependency. If you're aware of any strange edge cases that `intergraph` handles better than `tidygraph` I'll be happy to know about it.

cheers
