### ISSUE TITLE
access .orig_data  after a graph contraction

### ISSUE THREAD

**Issue by artxz** [thomasp85/tidygraph#170]
The node and edge data returned by `convert(tbl_graph, to_contracted, ...)`  contain a tibble-column ".orig_data". How should one access this? I tried `unnest_wider()` but it returned an error:

Error in `unnest_wider()`:
! `data` must be a data frame.

**Comment by thomasp85** [comment]
You really shouldn't concern yourself with that column as it is only there for internal use
