### ISSUE TITLE
Size aesthetic is deprecated for edges

### ISSUE THREAD

**Issue by jdfoote** [thomasp85/tidygraph#177]
I keep getting the following:

```
Warning: Using the `size` aesthetic in this geom was deprecated in ggplot2 3.4.0.
i Please use `linewidth` in the `default_aes` field and elsewhere instead.
```
I apologize, because I haven't done the work to figure out when it appears or looking into a patch, but I wanted to get this out there. I'll try to find time to do some more debugging. I assume it has to do with edge width.

**Comment by thomasp85** [comment]
this is a ggraph issue, not tidygraph. Closing here
