### ISSUE TITLE
mutate semantics

### ISSUE THREAD

**Issue by dahtah** [thomasp85/tidygraph#22]
Great package! I've noticed a problem with the way mutate is implemented, which makes it break with the usual convention that in a sequence like
mutate(data,a=...,b=a+...)
variables are defined sequentially and "a" is therefore available when defining "b".  The problem occurs when using graph traversal functions like map_bfs_dbl: 
```
#Works: variable r is created in its own call to mutate 
create_lattice(5) %>% activate(nodes) %>% mutate(r=1:5) %>% mutate(val=map_bfs_dbl(1,.f=function(node,path,...) .N()$r[node])) 

#Doesn't work: r is not yet available in .N()
create_lattice(5) %>% activate(nodes) %>% mutate(r=1:5,val=map_bfs_dbl(1,.f=function(node,path,...) .N()$r[node])) 
```

Perhaps set_graph_data should be called after each new variable is defined?

**Comment by thomasp85** [comment]
I am aware of this and was intending to document it more prior to release, but forgot. I personally eer to the current solution and then document that the graph is only updated after each verb is done, as the other approach will lead down a rabbit hole of problems...

**Comment by thomasp85** [comment]
On second thought it might not be so problematic. I do have some concerns over how it will affect speed but they may be unwarranted. I will look into it when I get some free time for it
