### ISSUE TITLE
Enhancement Suggestion - Incorporate into Tidyverse

### ISSUE THREAD

**Issue by digital-dharma** [thomasp85/tidygraph#31]
This is an excellent package - Any consideration or possibility of incorporating it into the standard tidyverse?

https://www.tidyverse.org/

**Comment by thomasp85** [comment]
Happy you like it. Its possible inclusion in the tidyverse package is really outside of my reach and at the mercy of @hadley. 

Its only a small convenience from a user perspective however. It works fine as an “external” package

**Comment by hadley** [comment]
We don't yet have a policy about packages that provide tidy APIs (like tidygraph, tidytext etc). At a minimum we need to highlight them on the website, and think through some semi-formal badging process.

**Comment by digital-dharma** [comment]
@thomasp85 - Completely agree, adding it to the standard `tidyverse `library is a small convenience.  The larger benefit is to have it featured via the website.  I've noticed that such packages seem to rapidly grow a community, which begins to produce enhanced documentation such as the [RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/) and of course development.

Great work on the package!
