### ISSUE TITLE
Suggestion for tidygraph about db and viz.

### ISSUE THREAD

**Issue by harryprince** [thomasp85/tidygraph#41]
previously, there are lots of packages about the graph in R, however, convert each other is so redundant.

The graph is very useful in industrial anti-fraud and recommendation system, I am seeking some tools to do better graph analysis, but most of the solution is not elegant and unified.

* DB: rOpensci have developed `nodbi`, a nosql interface for DB connection. Maybe unified elasticsearch, HBase, Mongo, Redis, Druid in the future, so seeking tidygraph can integrate nodbi.

* Viz: DiagrammeR based on the browser which integrated with Shiny very well. in that, looking forward to add DiagrammeR into tidygraph.

Thanks for your job to unify the separate graph system.

## references

https://cran.r-project.org/web/packages/ggCompNet/vignettes/comparing-graph-drawing-speed.html

**Comment by thomasp85** [comment]
Thanks for your suggestions. When it comes to access to graph databases I have a vision of providing more or less the same functionality as `dbplyr` but I have not gotten to this yet. I'm pretty sure I'll start by looking into Neo4j and other databases supporting Cypher so I don't have to spread my work out too thin when it comes to translating the `tidygraph` API to query calls...

Regarding viz, then I have made a hard decision of keeping it out of `tidygraph`. My own work will focus on `ggraph` which is tightly coupled with `tidygraph` and I am thus unlikely to spend my time building around `DiagrammeR` - Others are welcome to pick up that mantle though...
