### ISSUE TITLE
`filter` broken when result should be empty

### ISSUE THREAD

**Issue by AshesITR** [thomasp85/tidygraph#42]
Given some graph like this

```r
library(tidyverse)
library(tidygraph)

g <- tbl_graph(
    nodes = data_frame(id = letters[1:5]),
    edges = data_frame(from = c("a", "a", "b", "b", "c", "c"), 
                       to = c("b", "d", "c", "e", "d", "e"))
)
```

I expect the following three statements to yield identical graphs (namely, empty ones).
Currently, they don't. `g_false` and `g_missing_id` both instead contain `g` unmodified.

```r
g_false <- g %>% filter(FALSE)
g_missing_id <- g %>% filter(id == "f")
g_empty <- tbl_graph(
    nodes = data_frame(id = character()),
    edges = data_frame(from = character(), to = character())
)
```

If you provide an existing id (e.g. `g %>% filter(id == "c")`) filter works correctly.
Even `g %>% filter(sample(c(T,F), size = 5, replace = T))` works (with probability 2e-5).

I didn't find the root cause yet so no PR atm :(

**Comment by thomasp85** [comment]
Thanks - I’ll look into it
