### ISSUE TITLE
iterate verb

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/tidygraph#43]
something like

```r
gr %>%
  iterate(5, function() {
    # modify the graph
  })
```

and/or

```r
gr %>%
  iterate(graph_order() < 100, function() {
    # modify the graph
  })
```

**Comment by thomasp85** [comment]
Maybe this is more general than tidygraph - thoughts @hadley ?

**Comment by hadley** [comment]
What does `iterate()` do?

**Comment by thomasp85** [comment]
The goal of iterate is to modify the passed in tibble a number of times eg

```r
mtcars %>%
  iterate()
```

**Comment by hadley** [comment]
Like this?

```R
iterate <- function(x, n, f) {
  for (i in seq_len(n)) {
    x <- f(x)
  }
  x
}
```
?

**Comment by thomasp85** [comment]
Yeah - my phone typing submitted prematurely - I’ve updated the comment but your idea is right

**Comment by thomasp85** [comment]
Maybe have both an `iterate_while` and `iterate_n`

**Comment by thomasp85** [comment]
Any interest in this @hadley? Otherwise I'll just develop it in the context of tidygraph and you can jump in on a later stage...
