### ISSUE TITLE
Conversion from other structures

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/tidygraph#5]

**Comment by mdsumner** [comment]
I have done some work in this already, feel free to ping me for specific types you want converted. Most structures are either paths or primitives, and the sc PRIMITIVE table indexes between line segments and vertices:

https://github.com/mdsumner/scgraph/blob/master/README.md

One thing I want to do soon is extract the user-built structures from ggplot2, but happy to prioritize on other types that are important to you.

**Comment by thomasp85** [comment]
Support for all planned structures finalised with 55c99f5a76d0d7501ea657c076e203286e4057eb
