### ISSUE TITLE
Compute rowmeans with dplyr does not work

### ISSUE THREAD

**Issue by qinzhu** [thomasp85/tidygraph#57]
It seems using `df %>% dplyr::mutate(mean=rowMeans(.))` work for tibble but same command does not work with tidygraph object (with node data frame activated). It reports "Error in mutate_impl(.data, dots) : 
  Evaluation error: 'x' must be an array of at least two dimensions."

It would be great if same thing works directly on the graph object.

**Comment by thomasp85** [comment]
This is because `.` reference the object on the left-hand side of the pipe operator and there's no `rowMean` method for `til_graph` objects.

You can get the expected result by referencing the nodes directly in your `rowMean` call:

```r
as_tibble(volcano) %>% 
  tbl_graph() %>% 
  mutate(means = rowMeans(.N()))
```
