### ISSUE TITLE
Should activate use NSE

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/tidygraph#6]
There are really no prior art in this. On an abstract level activate references symbols in the data if `tbl_graph` is thought of as a named list with a `nodes` element containing the node tibble and a `edges` element containing the edge tibble. The normal verbs references the columns in the nibbles depending on which part is active, while the activate verb references the list of tibbles...

All in all, should the expected format be:

```r
gr %>% activate(nodes)
```

or

```r
gr %>% activate("nodes")
```

As this could affect future multi table API's I hope @hadley will chip in...

**Comment by thomasp85** [comment]
Currently it supports both with:

```r
activate.tbl_graph <- function(.data, what) {
  what_name <- deparse(substitute(what))
  if (what_name %in% c('nodes', 'edges')) what <- what_name
  active(.data) <- what
  .data
}
```

where NSE takes precedence, that is, if `nodes` is passed to the function it will not get evaluated even though a `nodes` variable is in scope...

**Comment by hadley** [comment]
Never try and do both with one function. I think that's a recipe for confusion.  I don't have a strong feeling either way for whether strings or expressions would be better.

**Comment by thomasp85** [comment]
With the depreciation of the `*_` functions in the devil version of `dplyr` I'm a bit unsure how SE should be handled. Is it up to the user to call it with `!!`?

**Comment by hadley** [comment]
Yes

**Comment by hadley** [comment]
We'll have more docs on this soon.

**Comment by thomasp85** [comment]
Thanks for the heads up - I want to have `activate` behave as close to `group_by` etc as possible so I'll hold of on this a bit and await more info

**Comment by thomasp85** [comment]
activate now uses the standard rlang tidyeval approach
