### ISSUE TITLE
coercion of phylo objects drops branch length data?

### ISSUE THREAD

**Issue by cboettig** [thomasp85/tidygraph#60]
Consider this example:

In `ape`, an example phylogeny has branch length data, which is reflected in the plot:

```r
library(ape)
data("bird.orders")
plot(bird.orders)
```

Note edge lengths differ based on the evolutionary distance separating the orders.   

```r
library(tidygraph)
library(ggraph)
bird <- as_tbl_graph(bird.orders) 
```

it appears the `bird` edge table has no length attributes.

**Comment by thomasp85** [comment]
Nice catch. I relied on ape's own igraph conversion and thought it would transfer everything... Will fix

**Comment by cboettig** [comment]
👏
