### ISSUE TITLE
issue with edge attributes when converting from `network` to `tbl_graph`

### ISSUE THREAD

**Issue by mkoohafkan** [thomasp85/tidygraph#69]
Probably related to [this issue on statnet/network](https://github.com/statnet/network/issues/4). Note my follow-up comment on the issue for additional info on the problem.

When converting a `network` object to a `tbl_graph`, edge attributes get jumbled. Consider the following example:

```
library(network)
# make a random directed graph
set.seed(10)
m <- matrix(rbinom(25,1,.4),5, 5)
diag(m) <- 0
g <- network(m, directed = TRUE)

# set an edge attribute
g.att = sample(LETTERS, length(g %e% "na"), replace = TRUE)
set.edge.attribute(g, "type", as.list(g.att))

as.edgelist(g, attrname = "type")
## note values of attribute "type"

library(tidygraph)
g.tbl = as_tbl_graph(g)
g.tbl %>% activate(edges)
## compare "type" attribute values to result of as.edgelist()
```

Doing `as_tbl_graph(intergraph::asIgraph(g))` seems to work ok.

**Comment by mkoohafkan** [comment]
It turns out there are a a lot of issues that can crop up when using edge attributes in `network`, e.g. cases where edges get dropped but the attribute values for those edges persist, etc. These issues can break the coercion to `igraph` and `tbl_graph` objects, but the issue is squarely on the `network` side.

**Comment by thomasp85** [comment]
Thanks for looking into this. Does this mean that the tidygraph conversion is technically correct, or are there other issues on the tidygraph side?

**Comment by thomasp85** [comment]
Thanks
