### ISSUE TITLE
How to filter for a set of nodes to keep all the edges connected to them?

### ISSUE THREAD

**Issue by kbzsl** [thomasp85/tidygraph#74]
How to filter for a set of nodes to keep all the edges connected to them?

The following code is not working as desired, because it will keep only the edges between the selected nodes:
```
tidy_graph_1 <- tidy_graph %>% 
  activate(nodes) %>%
  filter(node_name  %in% selected_nodes)
```

I am looking for a solution to keep all the edges including the edges towards nodes which are not included in the selected_nodes list but included in the original tbl_graph.

I can achieve it in the tidyverse (before creating the tbl_graph), but I am looking for a solution using the tidygraph.

**Comment by thomasp85** [comment]
It is not meaningful to have edges missing a terminal node, so `tidygraph` does the right thing. I'm curious what you expect the graph to look like if those edges were kept..?

**Comment by kbzsl** [comment]
Sorry, for ambiguous phrasing.
The real intention was to keep all the edges including the related far-end nodes, starting from a selected_nodes list. Now, I realized that my approach was faulty. 

Unfortunately still I can’t figure out a solution using tidygraph.

**Comment by thomasp85** [comment]
You could use map_local to see if each node is adjacent to any of the selected node, but I agree that it is not the most performant approach
