### ISSUE TITLE
Feature request: ggplot()/fortify() method for tbl_graph objects

### ISSUE THREAD

**Issue by dhicks** [thomasp85/tidygraph#78]
(Apologies if this feature has already been requested!  I didn't see anything looking through the issues.)  

A major part of the appeal of `tidygraph` for me is that I don't need to haul around 2 (or 3) separate objects with a network and the node (and/or edge) data.  But this functionality isn't quite there when it comes to plotting node (or edge) data using `ggplot()`.  For example, if I want to plot node statistics vs. gender or other demographics.  

Currently `tbl_graph` objects can't be fed directly into `ggplot()`.  For example, with 
```
hs = as_tbl_graph(highschool) %>%
    mutate(popular1 = centrality_degree(mode = 'in'), 
           popular2 = centrality_betweenness())
```
the following
```
ggplot(hs, aes(popular1, popular2)) +
    geom_point()
```
returns `Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class tbl_graph/igraph`.  

This isn't a huge deal because the workaround is to pass the `tbl_graph` object through `as_tibble()` or the equivalent:  
```
hs %>%
    as_tibble() %>%
    ggplot(aes(popular1, popular2)) +
    geom_point()
```

It seems like it would be straightforward to bundle this intermediate step into a `ggplot()` or `fortify()` method for `tbl_graph` objects.

**Comment by thomasp85** [comment]
tbl_graph objects can be plotted directly with ggraph which is ggplot’s network cousin

**Comment by dhicks** [comment]
Isn't this a different use case?  For example, I'm creating a scatterplot, not a network visualization.

**Comment by thomasp85** [comment]
Ah - sorry. I skimmed your post too quickly. I might consider a fortify method

**Comment by mkoohafkan** [comment]
Seems like for this use  case a `fortify` method would just run `as_tibble` on whichever table (node or edge) was `activate`d.
