### ISSUE TITLE
Add grouping factor in `tbl_graph`

### ISSUE THREAD

**Issue by DominiqueMakowski** [thomasp85/tidygraph#82]
Thanks for  the package. I am trying to use facetting based on a grouping factor. However, I have trouble understanding how it works. 

Basically, I'd like to "facet" the two following minimal graphs:

```r
# Group 1
tbl_graph(nodes = data.frame(label = c("A", "B", "C")), 
          edges = data.frame(
            from = c(1, 1, 2),
            to = c(2, 3, 3),
            group = c("G1", "G1", "G1"))) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link() +
  geom_node_text(aes(label=label))

# Group 2
tbl_graph(nodes = data.frame(label = c("A", "B", "C")), 
          edges = data.frame(
            from = c(1, 2),
            to = c(2, 3),
            group = c("G2", "G2"))) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link() +
  geom_node_text(aes(label=label))
```
![image](https://user-images.githubusercontent.com/8875533/49599155-940fe580-f980-11e8-9ccb-58aebde7f229.png)
![image](https://user-images.githubusercontent.com/8875533/49599177-9eca7a80-f980-11e8-994d-890034faf362.png)

First, I've tried the following, i.e. adding the grouping factor to the edges data:

```r
nodes <- data.frame(label = c("A", "B", "C"))
edges <- data.frame(from = c(1, 1, 2, 1, 2),
                    to = c(2, 3, 3, 2, 3),
                    group = c("G1", "G1", "G1", "G2", "G2"))
graph <- tbl_graph(nodes = nodes, edges = edges)

ggraph(graph, layout = "nicely") +
  geom_edge_link() +
  geom_node_text(aes(label=label)) +
  facet_graph(~group)
```

But it errors:
```
Error: At least one layer must contain all faceting variables: `group`.
* Plot is missing `group`
* Layer 1 is missing `group`
```

I've also tried adding the grouping factor to the nodes data, but it errored again...

```r
nodes <- data.frame(label = rep(c("A", "B", "C"), 2),
                    group = rep(c("G1", "G2"), each=3))
graph <- tbl_graph(nodes = nodes, edges = edges)

ggraph(graph, layout = "nicely") +
  geom_edge_link() +
  geom_node_text(aes(label=label)) +
  facet_graph(~group)
```
```
Error in gtable_add_grob(panel_table, axes$x$top, 1, panel_pos_col$l,  : 
  Not all inputs have either length 1 or same length same as 'grobs'
```

I am not sure wether the problem is related to `tbl_graph` or `facet_graph`. How  to correctly setup facetting using tbl_graph? Thanks a lot!

**Comment by jhrcook** [comment]
Hello,

Next time, I would recommend posting this on the [`ggraph` repo](https://github.com/thomasp85/ggraph). I think you are looking for `ggraph::facet_edges(~ group)`

```r
library(tidygraph)
library(tidyverse)
library(ggraph)

nodes <- data.frame(label = c("A", "B", "C"))
edges <- data.frame(from = c(1, 1, 2, 1, 2),
                    to = c(2, 3, 3, 2, 3),
                    group = c("G1", "G1", "G1", "G2", "G2"))
graph <- tbl_graph(nodes = nodes, edges = edges)

ggraph(graph, layout = "nicely") +
  geom_edge_link() +
  geom_node_text(aes(label=label)) +
  facet_edges(~group)
ggsave("test_graph.jpeg", dpi = 200)
```
![test_graph](https://user-images.githubusercontent.com/39419448/52736861-e7ae3900-2f98-11e9-9203-967c6ddd92ec.jpeg)

You can find great tutorials at [Thomas's blog](https://www.data-imaginist.com/2017/announcing-ggraph/).


Hope this helps,
Josh Cook

**Comment by thomasp85** [comment]
yeah, if you want to do faceting on tbl_graphs you should use the provided faceting functions in ggraph
