### ISSUE TITLE
bind_graphs() for list of tbl_graph objects

### ISSUE THREAD

**Issue by ananyabalakrishna** [thomasp85/tidygraph#88]
`bind_rows()` from the `dplyr` packages accepts a list of data frames as input. As far as I can tell, `bind_graphs()` only accepts individual `tbl_graph` objects as input, not a list of `tbl_graph` objects. 

```
networks <- list(network1, network2, network3)
bind_graphs(networks[[1]], networks[[2]], networks[[3]]) # This works.
bind_graphs(networks) # This doesn't work.
```
I use lists of networks and would find it useful if `bind_graphs` was to accept lists of networks as input. Thank you for this useful package.

**Comment by nilsreimer** [comment]
Apologies. I was logged into another account. I meant to open this issue from this account.

**Comment by mkoohafkan** [comment]
You can always do

```r
do.call(bind_graphs, networks)
```

But I agree that for symmetry it would be nice if `bind_graphs` could also accept a list of networks.
