### ISSUE TITLE
tbl_graph doesn't work as expected

### ISSUE THREAD

**Issue by fruchtblase** [thomasp85/tidygraph#89]
Hey,

I ran into an issue when creating graphs from dataframes

creating a graph with tbl_grap results an an error
` tbl_graph(nodes = nodes, edges = edgelist)`
> Error in (function (edges, n = max(edges), directed = TRUE)  : 
>   At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value

but doing the same with igraph directly works flawlessly:
`igraph::graph_from_data_frame(edgelist, vertices = nodes) %>% as_tbl_graph()`

R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
tidygraph_1.1.2

somebody on stackoverflow had a similar [problem](https://stackoverflow.com/questions/50457926/tidygraph-and-igraph-build-graph-from-dataframe-discrepancy)

**Comment by harryprince** [comment]
please provide a reproducible example by `reprex` package

**Comment by fruchtblase** [comment]
``` r
library(tidyverse)
library(tidygraph)

data <- jsonlite::fromJSON(url("https://api.semanticscholar.org/v1/author/1741101"))
nodes <- tibble(id = data$papers$paperId,
                    name = data$papers$title)
n <- dim(nodes)[1]

edges <- tibble(from = nodes$id[sample.int(n = n,100)],
                    to = nodes$id[sample.int(n = n,100)])

graph <- tbl_graph(nodes = nodes, edges = edges)
#> Error in (function (edges, n = max(edges), directed = TRUE) : At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value

graph <- igraph::graph_from_data_frame(edges, vertices = nodes) %>% as_tbl_graph()
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by fruchtblase** [comment]
Here is the reprex! 
Btw, the error doesn't show up if you drop the name column in the node dataframe.

``` r
library(tidyverse)
library(tidygraph)
#> 
#> Attaching package: 'tidygraph'
#> The following object is masked from 'package:stats':
#> 
#>     filter


data <- jsonlite::fromJSON(url("https://api.semanticscholar.org/v1/author/1741101"))
nodes <- tibble(id = data$papers$paperId,
                    name = data$papers$title)
n <- dim(nodes)[1]

edges <- tibble(from = nodes$id[sample.int(n = n,100)],
                    to = nodes$id[sample.int(n = n,100)])

graph <- tbl_graph(nodes = nodes, edges = edges)
#> Error in (function (edges, n = max(edges), directed = TRUE) : At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value

graph <- igraph::graph_from_data_frame(edges, vertices = nodes) %>% as_tbl_graph()
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by harryprince** [comment]
this code works well on my Mac

```
Package: tidygraph
Type: Package
Title: A Tidy API for Graph Manipulation
Version: 1.0.0
Date: 2017-07-06
Author: Thomas Lin Pedersen
Maintainer: Thomas Lin Pedersen <thomasp85@gmail.com>
Description: A graph, while not "tidy" in itself, can be thought of as
        two tidy data frames describing node and edge data
        respectively. 'tidygraph' provides an approach to manipulate
        these two virtual data frames using the API defined in the
        'dplyr' package, as well as provides tidy interfaces to a lot
        of common graph algorithms.
License: GPL (>= 2)
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.0.1
Imports: tibble, dplyr (>= 0.7), igraph, magrittr, utils, rlang, R6,
        Rcpp, tools, stats, tidyr
URL: https://github.com/thomasp85/tidygraph
BugReports: https://github.com/thomasp85/tidygraph/issues
LinkingTo: Rcpp
Suggests: network, data.tree, ape, graph, methods, testthat, covr
NeedsCompilation: yes
Packaged: 2017-07-06 11:40:22 UTC; thomas
Repository: CRAN
Date/Publication: 2017-07-07 05:01:15 UTC
Built: R 3.4.1; x86_64-apple-darwin15.6.0; 2017-07-25 17:51:07 UTC;
        unix
```

**Comment by fruchtblase** [comment]
interesting, when I downgraded to tidygraph 1.0.0 the code worked on my machine as well!
looks like this bug is only present in versions >= 1.1.0

**Comment by harryprince** [comment]
@thomasp85 might be aware this issue.

**Comment by aterhorst** [comment]
I experienced same issue. I renamed in my node list column name = 'name' to another column name and hey presto, all is good. It seems tbl_graph does not like node list to have columns labeled 'name'. BTW, my original node list has two columns, id = integer, name = character. I am using tidygraph version .1.1.12 on a Mac.

**Comment by aterhorst** [comment]
BTW, I was the person who reported the issue on https://stackoverflow.com/questions/50457926/tidygraph-and-igraph-build-graph-from-dataframe-discrepancy.

This is a different issue.

**Comment by thomasp85** [comment]
The issue is that igraph treats a node attribute named 'name' special and will try to match edges to that column if the edges are given as characters. The change was introduced because of reports that tidygraph did not construct the same graphs as igraph, but it seems that it was never documented. I'll add documentation

**Comment by thomasp85** [comment]
In addition to better documentation you can now also control which column is used for matching a character edgelist to nodes. It default to the old behaviour (i.e. using the `name` column)
