### ISSUE TITLE
replace values in node table

### ISSUE THREAD

**Issue by stevepowell99** [thomasp85/tidygraph#90]
I have a shiny app in which I use an editable table displaying the nodes data from a tbl_graph. The user can update individual values in the table and should be able to click to update the nodes table in the graph, But I don't know how to do that. The best I can do is this:

```
rstat_nodes <- data.frame(label = c("Hadley", "David", "Romain", "Julia"),stringsAsFactors = F)
rstat_edges <- data.frame(from = c(1, 1, 1, 2, 3, 3, 4, 4, 4), 
                          to = c(2, 3, 4, 1, 1, 2, 1, 2, 3))

g=tbl_graph(nodes = rstat_nodes, edges = rstat_edges)

mytable= g %>% activate(nodes) %>% as_tibble()

# simulate how the user modifies the table in the app

mytable[1,1]="Hardy"

# now I want to put the modified data back into the tbl_graph

g=g %>% activate(nodes) %>% mutate(label=mytable$label)

```
... but that seems tedious -- my actual table has many, unpredictable columns all of which should be replaced in this way. Wondering if there is a more elegant approach?

Great package by the way, thanks.

**Comment by stevepowell99** [comment]
I guess I could also just do 

`g=tbl_graph(mytable, g %>% activate(edges) %>% as_tibble)`

providing again that no nodes have been added or deleted. But it seems like a really violent way to do it.

**Comment by thomasp85** [comment]
If the user facing tables are the "ground truth" as to how the network should look, I think it makes sense to simply rebuild the network at every change and cache it
