### ISSUE TITLE
feature request: simple filtering

### ISSUE THREAD

**Issue by randomgambit** [thomasp85/tidygraph#92]
Hi @thomasp85 

Unless is am mistaken, I dont think there is an easy way to filter the nodes based on an edge condition. For instance, have a look here https://stackoverflow.com/questions/56640978/filter-in-a-tidygraph

the coertion to `igraph::as_data_frame()` looked promising, but it removes all the edge + nodes additional variables. 

Am I missing something? Or could you implement a simple `filter_node()` function?

Thanks!

**Comment by thomasp85** [comment]
For that particular example you'd do

```r
mygraph %>% 
  activate(edges) %>% 
  filter(power == 3) %>%
  activate(nodes) %>%
  filter(!node_is_isolated())
```

I'm unsure what *node filtering based on edges* would mean more generally as there is not a one to one mapping between nodes and edges

**Comment by randomgambit** [comment]
Ah! that is pretty useful! Thanks Thomas! 

Time permitting, I think this example could be added to the vignettes.

I think I found out another solution. 
What do you think of this?

```
tbl_graph(nodes = mynodes, edges = myedges) %>% 
  activate(edges) %>% 
  filter(power == 3) %>%
  activate(nodes) %>% 
  filter(id %in% union(.E()$to, .E()$from))

```
 Is that a proper use of the (immensely powerful) `.E()` and `.N()` that are not too much documented?

Thanks!!

**Comment by randomgambit** [comment]
> I'm unsure what node filtering based on edges would mean more generally as there is not a one to one mapping between nodes and edges

Well to be honest there is an asymmetry  right now on how `filter` works in `tidygraph`. If I filter the nodes, then the disconnected edges disappear as well. If I filter the edges, then all the nodes remain.

**Comment by thomasp85** [comment]
That is because it is perfectly legal to have nodes without edges, but an edge cannot exist without terminal nodes

**Comment by thomasp85** [comment]
regarding your question about `.E()` etc, that is surely a way to do it but using `node_is_isolated()` is clearer and more performant

**Comment by randomgambit** [comment]
thanks that's very useful

**Comment by randomgambit** [comment]
@thomasp85 there is something I quite dont understand. Is it a bug? am I misunderstanding the api call?

Consider this
```

mynodes <- tibble(id = c(1,2,3,4,5),
                  group = c(2,2,2,3,3))

myedges <- tibble(from = c(1,1,1,5),
                  to = c(5,2,3,4),
                  power = c(3,3,10,3))

mynet <- tbl_graph(nodes = mynodes, edges = myedges) %>% 
  activate(edges) %>% 
  filter(power == 3) %>%
  activate(nodes) %>% 
  filter(id %in% union(.E()$to, .E()$from))
# A tbl_graph: 4 nodes and 3 edges
#
# A rooted tree
#
# Node Data: 4 x 2 (active)
     id group
  <dbl> <dbl>
1     1     2
2     2     2
3     4     3
4     5     3
#
# Edge Data: 3 x 3
   from    to power
  <int> <int> <dbl>
1     1     4     3
2     1     2     3
3     4     3     3
```

As you can see, there are only 3 edges, and in reality only one can be plotted because node `3` is not in the `node` dataset.

However, the plot I get is quite surprising

```
mynet  %>%
 ggraph(layout = 'grid') + 
  geom_node_point() +
  geom_edge_arc() + 
  geom_node_text(aes(label = id), repel = TRUE) +
  theme_graph()
```

![image](https://user-images.githubusercontent.com/8282510/59693829-864fde00-91b5-11e9-97c7-07857e1f35fb.png)


Where are these additional arcs coming from? 4 and 5 are not connected in the edge data.
Thanks!

**Comment by randomgambit** [comment]
@thomasp85 it is as if `gggraph` ignores the line `  filter(id %in% union(.E()$to, .E()$from))` just before drawing the network...

**Comment by randomgambit** [comment]
after some exploration. It likely a bug. I think a new node is created to make up for the missing node, but then the labels are not correct (and all of this happens silently) https://stackoverflow.com/questions/56654033/understanding-a-simple-network-chart?noredirect=1#comment99878431_56654033

**Comment by thomasp85** [comment]
from and to does not refer to any column in your nodes table but to the index of the node in the table... therefore there are no edges in your `mynet` that cannot be plotted, they are all valid.

**Comment by randomgambit** [comment]
ohhh.. what you mean is that the true `id` is the index of the `node` dataframe? The one that is 1,2,3 and 4? In other words my column `ID` in the node dataframe is completely useless??

**Comment by thomasp85** [comment]
I wouldn't say completely useless :-). it just doesn't match to the to and from columns in the edgelist

**Comment by randomgambit** [comment]
thanks for this important clarification then. 

So if I understand well I cannot choose my own indexes (for the nodes). Therefore the safest way to construct a tidygraph network is to start with the edge dataframe (with to and from columns) and call as_`tbl_graph` so that the nodes are correctly created indexed. Even so, what about the nodes with no connections at all? How can I make sure it is indexed correctly? Does that make sense?

Thanks again!

**Comment by thomasp85** [comment]
there is nothing unsafe about your current approach. To and From matches to the index in your nodes table. I don't understand what the issue is with isolated nodes?

**Comment by randomgambit** [comment]
the issue is that because I export the nodes tables at various stages and perform a few operations on them (outside of tidygraph) I need to retain control of the rownames (i.e. the indexes) of the nodes.

I think the best way to proceed is to actually create the rownames myself, something like

```
tibble(myid = c(1,2,4,5),
          node_var = c('a','b','c','d')) %>% column_to_rownames(var = 'myid')

  node_var
1        a
2        b
4        c
5        d
```

Sorry if this is confusing but a lot of `tidygraph` tutorials are a bit ambiguous on that point, so it is easy to believe that the id used in the edge tables IS the ID column in the node tables (whereas it is the row names!)

**Comment by thomasp85** [comment]
it is not the row names. tidygraph doesn't care about the row names. it is simply the position in the node table... If you do non-tidygraph operations on your node and/or edge tables its up to yourself to keep track of it...

**Comment by randomgambit** [comment]
ohhh (again) so what `2` means in the `to` and `from` column of the edges tables is simply **second row** of the node table??

**Comment by thomasp85** [comment]
yes :-)

**Comment by randomgambit** [comment]
haha OK!!! so I guess to keep track of what `to` and `from` mean one MUST use `mutate(idx = row_number())` immediately after using `as_tibble()`. Otherwise there is no coming back!!!!

**Comment by randomgambit** [comment]
@thomasp85 I think this could be a nice warning to add for beginners like me that start using `tidygraph`. If you ever use `as_tibble()` on the nodes `tbl_graph` keep track of the `row_number()` because this maps to the edge data.

**Comment by thomasp85** [comment]
out of curiosity, why do you need to get it out of tidygraph during analysis?

**Comment by randomgambit** [comment]
well now that I understand better how indexing works, it is much simpler to keep the data within the tidygraph. :) however, I can think of situations where one wants to add some node- or edge- variables that depend on network metrics, but whose computation has to happen on a dataframe (for instance in a wide format). I will let you know if I find something else 👍

**Comment by randomgambit** [comment]
in any case, thanks for this amazing package!!
