### ISSUE TITLE
feature request: add more rows in the print method

### ISSUE THREAD

**Issue by randomgambit** [thomasp85/tidygraph#93]
Hi @thomasp85 ,

I often find myself struggling at quickly checking if my network metrics are correct. Indeed, the default `printing` method seems to return only the first 3 rows of the edge data.

Could it be possible to have something like  `options(tbl_graph.print_min = 20)` so that the user can choose how many rows to see? Exporting via `as_tibble()` is a bit of a hassle.

What do you think?
Thanks!

**Comment by randomgambit** [comment]
@thomasp85 I confirm. That would be incredibly useful.... that way you see the nodes and edges at once.

**Comment by randomgambit** [comment]
@thomasp85 or is there some temporary hack I can try to make that work? Not sure if you are planning to update this package soon...

Thanks!

**Comment by jameelalsalam** [comment]
I have also had this desire. There are different ways to approach it, but I went ahead and made a pull request that increases the defaults to 10 and 10, and allows user-specified `n` to the print method. https://github.com/thomasp85/tidygraph/pull/95

**Comment by randomgambit** [comment]
Thanks @jameelalsalam that looks great. I wonder if @thomasp85 had a chance to look at it :)

**Comment by jameelalsalam** [comment]
@randomgambit I think this package is on maintenance mode for the moment. Thomas has been very busy with ragg and other R graphics system packages, so he may not get to evaluate this for awhile. If you want the change sooner, you could install from source based on my PR branch (jameelalsalam/tbl-graph-print-n) or perhaps fork Thomas's repo and make the same change as the PR (just a couple characters change). For some reason the CRAN version is 1.1.2, but the Github version of the package is 1.1.1, I'm not sure if there are other changes not on Github.

**Comment by randomgambit** [comment]
noooo @thomasp85 dont abandon us!! :D
