### ISSUE TITLE
morph not working as expected

### ISSUE THREAD

**Issue by damianrt** [thomasp85/tidygraph#98]
I'm trying to identify dependencies between nodes in a directed acyclic graph.

igraph's dominator_tree() works as described using the example in the documentation, but I get an error when trying to use it in a tidygraph morph

```
library(igraph)
g <- graph_from_literal(R-+A:B:C, A-+D, B-+A:D:E, C-+F:G, D-+L,
                        E-+H, F-+I, G-+I:J, H-+E:K, I-+K, J-+I,
                        K-+I:R, L-+H)

dominator_tree(g, root="R")$domtree
```
```
IGRAPH d0d9370 DN-- 13 12 -- 
+ attr: name (v/c)
+ edges from d0d9370 (vertex names):
 [1] R->A R->B R->C R->D R->E C->F C->G D->L R->H R->I G->J R->K
```

Applying this to a tidygraph morph.
```
library(tidygraph)

g %>%
    as_tbl_graph() %>%
    morph(to_dominator_tree, root = "R", mode = "out") 
```
```
Error in if (is.numeric(v) && any(v < 0)) { : 
  missing value where TRUE/FALSE needed
```

Perhaps I have missed something. Is this a bug?

I posted this as a question on [stackoverflow](https://stackoverflow.com/questions/57421716/tidygraph-morph-error-trying-to-extract-a-subgraph-dominator-tree), but so far no feedback

**Comment by snystrom** [comment]
I think I am having the same issue. Either that or I don't correctly understand how morphers are supposed to work. In my case I am using `to_local_neighborhood`.

See [this question on stackoverflow](https://stackoverflow.com/q/57515804/8540339)

**Comment by mkoohafkan** [comment]
Probably related to #107 and issues with selecting nodes by name vs ID. However, in this case you should be able to use the `.N()` selector to pull the ID of the root:

```
library(igraph)
library(tidygraph)

g <- graph_from_literal(R-+A:B:C, A-+D, B-+A:D:E, C-+F:G, D-+L,
                        E-+H, F-+I, G-+I:J, H-+E:K, I-+K, J-+I,
                        K-+I:R, L-+H)

d1 = dominator_tree(g, root="R")$domtree


d2 = g %>%
    as_tbl_graph() %>%
    morph(to_dominator_tree, root = which(.N()$name == "R"), mode = "out") %>% 
	crystallize() 

bind_graphs(d2$graph[[1]], as_tbl_graph(d1)) %>% plot()
```
![image](https://user-images.githubusercontent.com/4790348/66866310-e0876280-ef4d-11e9-9c6c-78740c977415.png)

**Comment by thomasp85** [comment]
@mkoohafkan is correct. Tidygraph does not work with named nodes in general as I dislike how igraph treats certain magic node and edge attributes in a special way
